services:
  - Cyber-Ark Privileged Session Manager
  - TermService
vaultIniLocation: C:\Users\gleveill\Documents\Dev\go\Supervision\poubelle\Vault.ini
disks:
  - C
  - D
listeningPort: 38001
logLevel: debug