services:
  - Cyber-Ark Privileged Session Manager
  - TermService
#vaultIniLocation: Path\to\Vault.ini
disks:
  - C
  - D
listeningPort: 38001
logLevel: debug
#vaultsIP: 127.0.0.1,10.20.30.40
healthCheckInterval: 10  # seconds
connectionTimeout: 5     # seconds for vault connections
